"use client";
import Image from "next/image";import Link from "next/link";import {useEffect,useRef,useState} from "react";import {useRouter} from "next/navigation";import AlbumBook from "@/components/album-book";import {useAuth} from "@/components/auth-provider";import {GlobeIcon,UserIcon} from "@/components/icons";
type Theme="light"|"dark";
export default function HomeClient(){const router=useRouter();const [theme,setTheme]=useState<Theme>(()=>typeof document!=="undefined"&&document.documentElement.dataset.theme==="dark"?"dark":"light");const [gallery,setGallery]=useState(false);const dialogRef=useRef<HTMLDialogElement>(null);const startRef=useRef<HTMLButtonElement>(null);const auth=useAuth();
 useEffect(()=>{const open=()=>setGallery(true);addEventListener("crayon:open-gallery",open);return()=>removeEventListener("crayon:open-gallery",open)},[]);
 function toggleTheme(){const next=theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("crayon-theme",next);setTheme(next)}
 return <main className="studio-page"><div className="studio-scene studio-scene-day"/><div className="studio-scene studio-scene-night"/><div className="studio-light studio-light-day"/><div className="studio-light studio-light-night"/><div className="studio-grain"/>
 <div className="studio-content"><header className="site-header"><Link className="brand" href="/" aria-label="Crayon 首页"><span className="brand-mark"><i/><i/><i/></span><span>Crayon<span className="brand-dot">.</span></span></Link><span className="header-note">一张照片，一幅亲手画的画</span><div className="header-actions"><a className="header-icon-link glass-control" href="https://github.com/beststarli/crayon" target="_blank" rel="noopener noreferrer" aria-label="GitHub 仓库"><svg className="github-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.7a9.5 9.5 0 0 0-3 18.5c.5.1.7-.2.7-.5v-1.9c-2.8.6-3.4-1.2-3.4-1.2-.5-1.2-1.1-1.5-1.1-1.5-.9-.6.1-.6.1-.6 1 0 1.6 1 1.6 1 .9 1.6 2.4 1.1 3 .9.1-.7.4-1.1.7-1.4-2.2-.3-4.6-1.1-4.6-4.7 0-1 .4-1.9 1-2.6-.1-.3-.4-1.3.1-2.6 0 0 .8-.3 2.6 1a9 9 0 0 1 4.8 0c1.8-1.2 2.6-1 2.6-1 .5 1.3.2 2.3.1 2.6.7.7 1 1.6 1 2.6 0 3.6-2.4 4.4-4.6 4.7.4.3.7.9.7 1.8v2.8c0 .4.2.6.7.5A9.5 9.5 0 0 0 12 2.7Z"/></svg></a><a className="header-icon-link glass-control" href="https://www.beststarli.cn/" target="_blank" rel="noopener noreferrer" aria-label="访问博客"><GlobeIcon/></a><button className="header-icon-link glass-control" onClick={()=>auth.user?router.push("/account"):auth.openAuth()} aria-label={auth.user?"打开我的账户":"登录或注册"}>{auth.user?<span className="avatar-initial">{(auth.user.nickname||auth.user.username).slice(0,1).toUpperCase()}</span>:<UserIcon/>}</button><button className="theme-toggle glass-control" onClick={toggleTheme} aria-label={theme==="dark"?"切换至浅色模式":"切换至深色模式"}><svg className="sun-icon" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4m11.4-11.4 1.4-1.4"/></svg><svg className="moon-icon" viewBox="0 0 24 24"><path d="M20.5 14.2A8.5 8.5 0 0 1 9.8 3.5a8.5 8.5 0 1 0 10.7 10.7Z"/></svg><span className="theme-toggle-text">{theme==="dark"?"白天":"夜晚"}</span></button></div></header>
 <section className="hero product-hero" aria-labelledby="hero-title"><figure className="artwork"><div className="artwork-paper"><div className="artwork-image"><Image className="artwork-day" src="/images/flower-field-day.webp" alt="阳光下的油画棒花田" fill priority sizes="(max-width:640px) 82vw,46vw"/><Image className="artwork-night" src="/images/flower-field-night.webp" alt="夜色中的油画棒花田" fill priority sizes="(max-width:640px) 82vw,46vw"/></div><span className="artwork-tape artwork-tape-top-left"/><span className="artwork-tape artwork-tape-top-right"/><span className="artwork-tape artwork-tape-bottom-left"/><span className="artwork-tape artwork-tape-bottom-right"/></div><figcaption className="artwork-caption"><span>花田 / <span className="caption-day">晴日</span><span className="caption-night">入夜</span></span><span>OIL PASTEL STUDY · 01</span></figcaption></figure>
 <div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> WELCOME TO YOUR LITTLE STUDIO <span className="eyebrow-line"/></p><h1 id="hero-title">把喜欢的瞬间，<em>画下来。</em></h1><p className="hero-description">上传一张照片，让它变成油画棒的模样。<br/>再跟着简单的步骤，亲手画出属于你的作品。</p><div className="feature-actions"><button className="feature-button primary glass-control" ref={startRef} onClick={()=>dialogRef.current?.showModal()}><Image className="feature-icon" src="/icons/create-crayons-v2.png" alt="" width={36} height={36}/><span>开始创作</span></button><button className="feature-button secondary glass-control" onClick={()=>setGallery(true)}><Image className="feature-icon" src="/icons/artwork-album.png" alt="" width={36} height={36}/><span>我的画册</span></button><Link className="feature-button tertiary glass-control" href="/about"><Image className="feature-icon" src="/icons/about-magnifier.png" alt="" width={36} height={36}/><span>关于 Crayon</span></Link></div></div></section>
 <footer className="site-footer"><span>LET EVERY PHOTO BECOME A PAINTING</span><span>Copyright © BestStar. All rights reserved. · Crayon</span></footer></div>
 <AlbumBook open={gallery} onClose={()=>setGallery(false)}/><dialog className="preview-dialog" ref={dialogRef} onClose={()=>startRef.current?.focus()}><div className="preview-panel"><button className="dialog-close" onClick={()=>dialogRef.current?.close()} aria-label="关闭">×</button><span className="dialog-kicker">COMING SOON · 即将开放</span><h2>从一张照片，<br/>到一幅自己的画。</h2><p className="dialog-intro">创作工作台正在准备中，你将可以上传照片、选择画幅并跟着教程完成作品。</p><button className="dialog-done" onClick={()=>dialogRef.current?.close()}>我知道了</button></div></dialog></main>}
